# Generated by Django 3.2.4 on 2021-06-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0002_auto_20210615_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='ComentarioVuelo',
        ),
        migrations.RemoveField(
            model_name='comentariovuelo',
            name='Viaje',
        ),
        migrations.AddField(
            model_name='comentariovuelo',
            name='Vuelo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mipagina.vuelo'),
        ),
    ]
