# Generated by Django 3.2.4 on 2021-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0003_auto_20210615_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariovuelo',
            name='autor',
        ),
    ]
