# Generated by Django 3.2.4 on 2021-06-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0004_remove_comentariovuelo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariovuelo',
            name='comentario',
            field=models.TextField(default=''),
        ),
    ]
